### ISSUE TITLE
Salvage test suite to run in isolation, simplify CI

### ISSUE THREAD

**Issue by badgerassassin** [Badger-Finance/badger-system#106]
Fix test suite to remove calls to interface.<contract> which are in the global scope to fix common bug

Rename existing tests/ directory to something else where we can keep the scripts that depend on specific forks / networks / other than mainnet-fork

Add fork block to brownie-config.yaml so we can replicate the environment

Salvage tests which can run at the prescribed block and keep in the new tests/ directory

Anything which works with a static fork, keep

**Comment by sajanrajdev** [comment]
Closing this issue as it was split into issues #112, #113 and #114.
