### ISSUE TITLE
Chainlink hardcoded oracle bot script

### ISSUE THREAD

**Issue by dapp-whisperer** [Badger-Finance/badger-system#135]
The chainlink data updates at 2pm EST. Between 2pm & 3pm EST, the data must be posted to the medianOracle by calling getThePrice() on the adapter oracle (the adapter oracle simply converts latest chainlink data to 18 decimals and posts it to medianOracle)

Adapter oracle lives [here](http://etherscan.io/address/0xB572f69edbfC946af11a1b3ef8D5c2f41D38a642)

- Bot addresses will be added to ACL for calling oracle.

**Comment by mitche50** [comment]
@btcookies I believe this is complete, can you please close if so?

**Comment by btcookies** [comment]
Pretty sure @Darruma finished this?
