### ISSUE TITLE
ImmuniFi report:  Non-critical code issues in contracts/badger-sett/strategies/pancake/StrategyPancakeLpOptimizer.sol

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-system#194]
Note that neither of these issues have any security impact, but more reveal less than perfect coding styles and review processses.

Conversation with Immuifi:

Immunefi wrote a message

Hi,

a whitehat has identified a vulnerability in your application.

Following, the complete report:

Smart Contract Bug Description
I am reporting several issues here. In my opinion, these are too small to be reported separately and they are closely related to the same strategy.

Comment above says: "Performance fees are taken on Cake directly". However, actually the fees are deducted from LP token, not Cake: // Process performance fees in LP token harvestData.toStrategist = _processFee(want, lpAfterSell, performanceFeeStrategist, strategist); harvestData.toGovernance = _processFee(want, lpAfterSell, performanceFeeGovernance, IController(controller).rewards());

function _sellTokenForWant declares that it should return TokenSwapData but there is no return statement at the end so it basically returns a default empty struct. The return value is not used anywhere so there is no impact on calculations, etc.

07.30.2021 13:30 +0200
Badger DAO wrote a message

This sounds like a problem with our documentation that has no real effect on the users returns. The disclosure above has no link to said documentation, which maybe we should change. That being said, our BSC setts have very little AUM and the pancake emissions seem to be retiring, we are likely to retire these setts.

The most action we would take here to update our documentation. That being said, happy to pay a $250 bounty if the whitehat can provide a more detailed report that includes code samples (with context) and links to the contract the code was in, and a link to whatever documentation is incorrect.

07.31.2021 18:24 +0200
Immunefi wrote a message

Hi,

the whitehat has provided us updates, you can find them here.

Please, let us know how you'd like to proceed.

Best,
Simone

Whitehat's original message
A simplified code snippet demontrating that _sellTokenForWant assigns values to struct but does not return it:

struct TokenSwapData { address tokenIn; uint256 totalSold; } function _sellTokenForWant(address tokenIn, uint256 amount) public returns (TokenSwapData memory) { TokenSwapData memory swapData; swapData.tokenIn = tokenIn; swapData.totalSold = amount; }

Here is the contract we are talking about: https://github.com/Badger-Finance/badger-system/blob/beadfc54042ec57ae51534c252aa613bb630f60d/contracts/badger-sett/strategies/pancake/StrategyPancakeLpOptimizer.sol

Here the comment says "Performance fees are taken on Cake directly": https://github.com/Badger-Finance/badger-system/blob/beadfc54042ec57ae51534c252aa613bb630f60d/contracts/badger-sett/strategies/pancake/StrategyPancakeLpOptimizer.sol#L25

and here it actually deducts these fees from LP tokens: https://github.com/Badger-Finance/badger-system/blob/beadfc54042ec57ae51534c252aa613bb630f60d/contracts/badger-sett/strategies/pancake/StrategyPancakeLpOptimizer.sol#L268-L270

**Comment by Tritium-VLK** [comment]
Opened PR #193 to fix the comment.

 _sellTokenForWant issue.  It doesn't seem critical but it is wrong, and we have in the past tried to keep our code clean for others to look at.
 
 We will pay this Whitehat $250 for his report, as these things, at least the _sellTokenForWant issue should have been handled by the review board.

**Comment by Tritium-VLK** [comment]
Also added the return to the bottom of _sellTokenForWant

**Comment by sajanrajdev** [comment]
PR merged, closing this issue.
