### ISSUE TITLE
DefiDollar rewards are unclaimable

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/badger-system#210]
Reported on: 2021-08-09T01:32:47.779000+00:00
Bug Description:
Users with DFD rewards are unable to claim their balances, receiving an error stating that they are trying to claim more than their balance or an invalid cycle. They’re able to claim if they remove the DFD from the claim. 

https://media.discordapp.net/attachments/873031037851172945/873035243337170954/unknown.png

Attachments:

**Comment by Tritium-VLK** [comment]
resolved
