### ISSUE TITLE
Misleading error msg in StrategyBadgerLpMetaFarm contract

### ISSUE THREAD

**Issue by pauliax** [Badger-Finance/badger-system#7]
https://github.com/Badger-Finance/badger-system/blob/c67c41ecf8b07771c04a93b8011276e0eb615c24/contracts/badger-sett/strategies/native/StrategyBadgerLpMetaFarm.sol#L98-L102

`require(address(badger) != _asset, "geyser");`

imo error msg is misleading, should be:

`require(address(badger) != _asset, "badger");`

**Comment by dapp-whisperer** [comment]
Agreed, will change in the file. We're going to move to an array of protected tokens in the future.
